##### 10-Mar-22

## iNeuron Programming Assignment 9

#### 1. Write a Python Program to add two matrices?

In [1]:
import numpy as np

# 1-D matrix
arr1 = np.arange(10)
arr2 = np.arange(10,20)
arr1,arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [2]:
arr1+arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [3]:
# 2-D matrices
arr1 = np.matrix('1 2; 3 4')
arr1

matrix([[1, 2],
        [3, 4]])

In [4]:
arr2 = np.matrix('10 20; 30 40')
arr2

matrix([[10, 20],
        [30, 40]])

In [5]:
arr1 + arr2

matrix([[11, 22],
        [33, 44]])

#### 2. Write a python program to multiply two matrices?

In [6]:
arr_m = arr1*arr2
arr_m

matrix([[ 70, 100],
        [150, 220]])

#### 3. Write a Python program to transpose a matrix

In [7]:
arr_m.transpose()

matrix([[ 70, 150],
        [100, 220]])

#### 4. Write a Python program to sort words in alphabetical order

In [8]:
words = 'Write a Python program to sort words in alphabetical order'
words = words.split()
words = [i.lower() for i in words] # Converting all the words to lower, else capitalized words will be sorted first

In [9]:
words.sort()
words

['a',
 'alphabetical',
 'in',
 'order',
 'program',
 'python',
 'sort',
 'to',
 'words',
 'write']

#### 5. Write a Python program to remove punctuation from a string?

In [10]:
sentence = "This, i$ @ -- sentence w!th l*ts of punctuations!?"

import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
for i in string.punctuation:
    sentence = sentence.replace(i,'')
sentence

'This i   sentence wth lts of punctuations'