##### 22-08-2021

# Python Programming Assignment 7

#### 1. Write a Python Program to find sum of array?

In [1]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
def sumofarray(arr):
    print(f'Sum of array {arr} = {np.sum(arr)}')

sumofarray(np.arange(10))

Sum of array [0 1 2 3 4 5 6 7 8 9] = 45


#### 2. Write a Python Program to find largest element in an array?

In [3]:
def maxofarray(arr):
    print(f'Largest element of array {arr} = {np.max(arr)}')

maxofarray(np.arange(10))

Largest element of array [0 1 2 3 4 5 6 7 8 9] = 9


#### 3. Write a Python Program for array rotation?

In [4]:
def arrayrotate(arr,n):
    temp = [0]*len(arr)
    for i in range(len(arr)):
        if (i+n)<10:
            temp[i] = arr[i+n]
            print(temp[i])
    for i in range(n):
        temp[-(i+1)]=arr[n-i-1]
    print(temp)

arrayrotate(np.arange(10),4)

4
5
6
7
8
9
[4, 5, 6, 7, 8, 9, 0, 1, 2, 3]


#### 4. Write a Python Program to Split the array and add the first part to the end?

In [5]:
arr = np.arange(10)

np.append(arr[5:],arr[:5])

array([5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [6]:
def splitnadd(arr, n):
    return np.append(arr[n:],arr[:n])

print(splitnadd(np.arange(10),5))

[5 6 7 8 9 0 1 2 3 4]


#### 5. Write a Python Program to check if given array is Monotonic?

In [7]:
arr = np.array([1,4,5,7,8,3])

In [8]:
def monotonic_check(arr):
    flag = False
    i=0
    if arr[i]<arr[i+1]:
        print("Increasing Monotonic check")
        for i in range(len(arr)-1):
            if arr[i]<arr[i+1]:
                flag = True
                continue
            else:
                flag = False
                break
    i=0
    if arr[i]>arr[i+1]:
        print("Decreasing Monotonic check")
        for i in range(len(arr)-1):
            if arr[i]>arr[i+1]:
                flag = True
                continue
            else:
                flag = False
                break
    print(flag)

In [9]:
monotonic_check([9,7,6,5,3,1,2])

Decreasing Monotonic check
False


In [10]:
monotonic_check([9,7,6,5,3,1,0])

Decreasing Monotonic check
True


In [11]:
monotonic_check(np.arange(10))

Increasing Monotonic check
True
